name: Build & Release Backend

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings

  build:
    needs: test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build EXE (PyInstaller)
        shell: pwsh
        run: |
          if (Test-Path "setup.spec") {
            pyinstaller setup.spec
          } else {
            pyinstaller --onefile --name "Back-End InventoryApp" setup.py
          }
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-exe
          path: backend/dist/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-exe
          path: dist/
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
