name: Build and Release Backend EXE

on:
  push:
    tags:
      - 'v*'  # Trigger saat push versi

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        cd backend
        pyinstaller inventory.spec

    - name: Upload EXE to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: backend/dist/Back-End\ InventoryApp.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
